# Generated by Django 4.2.7 on 2023-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatus',
            name='imagen',
            field=models.ImageField(default=1, upload_to='estatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logro',
            name='imagen',
            field=models.ImageField(default=1, upload_to='logros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='imagen',
            field=models.ImageField(default=2, upload_to='nivel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opcionespregunta',
            name='contenido_opcion',
            field=models.CharField(max_length=100),
        ),
    ]
