# Generated by Django 4.2.7 on 2023-11-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estatus_imagen_logro_imagen_nivel_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='imagen',
            field=models.ImageField(upload_to='media/nivel'),
        ),
    ]
