# Generated by Django 4.2.7 on 2023-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nivel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='nivel'),
        ),
    ]
